name: CI - clientes

on:
  pull_request:
    branches: [develop]
    paths:
      - 'clientes/**'
  push:
    branches: [ test/ci-cd ]

jobs:
  IC_clientes:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: clientes

    steps:
      # 1) Descargar el código del repositorio
      - name: Download code
        uses: actions/checkout@v3

      # 2) Configurar Node.js (versión estable para React Native)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.4'
          cache: 'npm'
          cache-dependency-path: clientes/package-lock.json

      #3) Instalar dependencias
      - name: Install dependencies
        run: npm ci --no-audit --no-fund
        #run: npm install

      # 4) Ejecutar pruebas de Jest
      - name: Run Jest
        run: npm test -- --ci --maxWorkers=50%

      # 5) Generacion de reportes de cobertura
      - name: Upload coverage summary (LCOV)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: ventas/coverage/lcov.info

      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: ventas/coverage